databases:
  - name: conecta-servicos-db
    plan: free

services:
  - type: web
    name: conecta-servicos
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn logo_feature:app
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: conecta-servicos-db
          property: connectionString
